#!/usr/bin/env bash
# Single-script reproduction of the Qwen3.8-27B KLD campaign results.
#
#   scripts/reproduce.sh
#
# What it does, in order:
#   0. environment  — scripts/setup_env.sh (unless .env already exists):
#                     clones vllm/b12x at the pinned commits in
#                     configs/environment.lock, builds the venv + EXL3 ext.
#   1. integrity    — verifies the frozen token window sha256.
#   2. references   — BF16 (b12x) captures + runtime floor probe (gate)
#                     (acceptance gate: floor probe must read ~0; see
#                     docs/METHODOLOGY.md §6).
#   3. sweep        — every candidate in configs/models.yaml, two
#                     fresh-process captures + comparisons each.
#   4. verify       — compares the rerun numbers against the committed
#                     expected numbers (results/comparisons/ snapshot taken
#                     before the rerun) via scripts/verify_repro.py.
#
# Cost: ~500 GB of model downloads (HF hub, pinned revisions) and many GPU
# hours on one 96 GB-class Blackwell GPU. Individual labels can be run with
# scripts/run_campaign.sh <label>; only the aggregate rerun needs this script.
#
# Tolerances for step 4: KLD_TOL / TOP1_TOL env (defaults in verify_repro.py).
# On the identical GPU + engine commit the floor is bit-exact 0.0 and repeats
# are bit-identical, so KLD_TOL=0 TOP1_TOL=0 is a valid strict rerun check.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO"

echo "== [0/4] environment"
if [[ ! -f .env ]]; then
  scripts/setup_env.sh
fi
set -a; source .env; set +a

echo "== [1/4] token window integrity + registry preflight"
python3 scripts/preflight_repos.py
python3 - <<'EOF'
import hashlib, json
man = json.load(open("data/tokens.manifest.json"))
raw = open(man["tokens_file"], "rb").read()
got = hashlib.sha256(raw).hexdigest()
assert got == man["sha256"], f"token file sha256 mismatch: {got} != {man['sha256']}"
print(f"token window OK ({man['n_tokens']} tokens, {got[:12]}…)")
EOF

echo "== snapshot committed expectations before any writes"
rm -rf results/expected
mkdir -p results/expected
cp results/comparisons/*.json results/expected/

echo "== [2/4] reference captures + floor probe"
scripts/run_campaign.sh ref
python3 - <<'EOF'
import json
f = json.load(open("results/comparisons/floor_probe.json"))
assert f["mean_kld"] <= 1e-6, f"floor probe {f['mean_kld']} > 1e-6 — engine not deterministic, do not trust the ladder (docs/METHODOLOGY.md §6)"
print(f"floor probe OK: mean KLD {f['mean_kld']:.3e}, top-1 {f['top1_agreement']:.4f}")
EOF

echo "== [3/4] full sweep"
scripts/run_campaign.sh all

echo "== [4/4] verify rerun vs committed expectations"
"$KLD_PY" scripts/verify_repro.py results/expected results/comparisons \
  ${KLD_TOL:+--kld-tol "$KLD_TOL"} ${TOP1_TOL:+--top1-tol "$TOP1_TOL"}
scripts/run_campaign.sh report
echo "REPRODUCE OK — see results/RESULTS.md (regenerated by make_report.py if desired)"
