#!/usr/bin/env bash
# One-time environment setup for the Qwen3.8-27B KLD campaign.
# Clones the runtime repos at the EXACT pinned commits from
# configs/environment.lock, builds a venv, JIT-builds the EXL3 extension,
# and writes the resulting paths back into .env.
#
#   scripts/setup_env.sh            # create $KLD_WORKDIR and .env
#   SKIP_VENV_VERIFY=1 ...          # skip the import smoke checks
#
# Requires: python >= 3.12 (3.12.13 at capture time), git, nvcc + CUDA 13
# toolkit reachable from the shell (the pinned torch is cu130), ~150 GB disk
# for the venv + source trees. GPU needed only for the final smoke test.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LOCK="$REPO/configs/environment.lock"

get() { grep -E "^$1:" "$LOCK" | head -1 | sed -E 's/^[^:]+:[[:space:]]*//'; }
VLLM_REPO=$(get vllm_repo);   VLLM_COMMIT=$(get vllm_commit)
B12X_REPO=$(get b12x_repo);   B12X_COMMIT=$(get b12x_commit)
EXL3_PKG=$(get exllamav3_pypi)

# read existing .env (if any) for KLD_WORKDIR overrides
[[ -f "$REPO/.env" ]] && set -a && source "$REPO/.env" && set +a
WORKDIR="${KLD_WORKDIR:-$HOME/kld-env}"
mkdir -p "$WORKDIR"
echo "== setup_env: workdir=$WORKDIR"

clone_at() { # clone_at <url> <commit> <dir>
  local url=$1 commit=$2 dir="$WORKDIR/$3"
  if [[ -d "$dir/.git" ]]; then
    echo "== $3 exists; fetching"
    git -C "$dir" fetch origin "$commit" 2>/dev/null || git -C "$dir" fetch origin
  else
    echo "== cloning $url -> $dir"
    git clone "$url" "$dir"
  fi
  git -C "$dir" checkout -q "$commit"
  echo "   $3 @ $(git -C "$dir" rev-parse HEAD)"
}

clone_at "$VLLM_REPO" "$VLLM_COMMIT" vllm
clone_at "$B12X_REPO" "$B12X_COMMIT" b12x

VENV="$WORKDIR/.venv"
if [[ ! -x "$VENV/bin/python" ]]; then
  echo "== creating venv at $VENV"
  if command -v uv >/dev/null 2>&1; then
    uv venv --python 3.12 "$VENV"
  else
    python3.12 -m venv "$VENV"
  fi
fi
PY="$VENV/bin/python"
PIP() { if command -v uv >/dev/null 2>&1; then uv pip install --python "$PY" "$@"; else "$PY" -m pip install "$@"; fi; }

echo "== installing b12x (editable, pinned tree) + EXL3 ext sources"
PIP -e "$WORKDIR/b12x"
PIP "$EXL3_PKG"

echo "== installing vLLM fork (editable, pinned tree; pulls torch/flashinfer pins)"
# Builds vllm from source at the pinned commit; needs nvcc + ~30 min.
PIP -e "$WORKDIR/vllm"

echo "== JIT-building exllamav3_ext (EXL3 CUDA extension)"
mkdir -p "$WORKDIR/torch_extensions"
TORCH_EXTENSIONS_DIR="$WORKDIR/torch_extensions" "$PY" - <<'EOF'
import exllamav3.ext  # noqa: F401  (module import triggers cpp_extension.load)
EOF
EXT_DIR=$(find "$WORKDIR/torch_extensions" -maxdepth 2 -name 'exllamav3_ext*.so' -printf '%h\n' | head -1)
if [[ -z "${EXT_DIR:-}" ]]; then
  echo "!! exllamav3_ext .so not found under $WORKDIR/torch_extensions — EXL3 candidates will fail to load" >&2
else
  echo "   exllamav3_ext at: $EXT_DIR"
fi

if [[ "${SKIP_VENV_VERIFY:-0}" != "1" ]]; then
  echo "== verifying imports"
  "$PY" - <<'EOF'
import vllm, b12x, torch
from importlib.metadata import version as _v
print("vllm", vllm.__version__)
print("torch", torch.__version__)
assert "exl3" in __import__("vllm.model_executor.layers.quantization", fromlist=["QUANTIZATION_METHODS"]).QUANTIZATION_METHODS, \
    "exl3 missing from QUANTIZATION_METHODS — wrong vllm commit?"
assert _v("b12x"), "b12x import failed"
assert _v("exllamav3"), "exllamav3 install missing"
EOF
fi

echo "== writing .env"
cat > "$REPO/.env" <<EOF
# Generated by scripts/setup_env.sh on $(date -u +%FT%TZ). Machine-local.
KLD_PY=$PY
KLD_WORKDIR=$WORKDIR
KLD_GPU_IDS=$(grep '^KLD_GPU_IDS=' "$REPO/.env" 2>/dev/null | tail -1 | cut -d= -f2)
KLD_GPU_IDS=${KLD_GPU_IDS:-${KLD_GPU_IDS_ENV:-0}}
KLD_TP=${KLD_TP:-1}
VLLM_EXL3_EXT_PATH=${EXT_DIR:-}
KLD_GPU_MEM_UTIL=${KLD_GPU_MEM_UTIL:-0.90}
EOF

echo
echo "done. Next: edit .env if needed (KLD_GPU_IDS), then run"
echo "  scripts/run_campaign.sh ref          # reference captures + floor probe"
echo "  scripts/run_campaign.sh all        # full sweep"
echo "or the full verification pipeline: scripts/reproduce.sh"
